spring:
  application:
    name: security-jwt-template

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: false

jwt:
  secret: ${SPRING_JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 21600000
