name: "🧪 Test"
description: "테스트 코드 작성 또는 개선 관련 이슈"
labels: ["test"]
body:
  - type: textarea
    attributes:
      label: 🧩 테스트 그룹 (Group)
      description: 해당 테스트가 속하는 모듈, 기능 또는 클래스 등을 작성해주세요.
      placeholder: 예) 사용자 로그인 기능, 주문 생성 API 등
    validations:
      required: false

  - type: textarea
    attributes:
      label: 🔍 상세 설명 (Detail)
      description: 어떤 테스트를 작성하거나 수정해야 하는지 설명해주세요.
      placeholder: 예) 로그인 실패 케이스 누락, 예외 처리 테스트 필요 등
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업 항목 (Todo)
      description: 테스트 작업 항목을 체크박스로 나열해주세요.
      placeholder: |
        - [ ] 실패 케이스 테스트 추가
        - [ ] Mock 객체 적용
        - [ ] 커버리지 90% 이상 맞추기
